[server]
maxUploadSize = 3000
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 2000
headless = true
runOnSave = true
browser.gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 
