[server]
maxUploadSize = 2000
enableCORS = true
enableXsrfProtection = true
maxMessageSize = 2000

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 
